# https://github.com/actions/virtual-environments/tree/main/images/macos
name: python_on_macos
on: [pull_request, push]
jobs:
  python_on_macos:
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          python --version
          python2 --version
          python3 --version
          python2 -m pip install --upgrade pip
          python3 -m pip install --upgrade pip
      - run: |
          python2 -m pip install flake8
          python2 -m flake8 --version
                 
